### ISSUE TITLE
guidelines

### ISSUE THREAD

**Issue by klawr** [deeplex/deeplex.github.io#5]
Add guidelines for all language in use to have a consistent code base for projects written in different languages.

## Tasks
- [ ] Add guidelines for C++
- [ ] Add guidelines for ESP32 configuration
- [ ] Add guidelines for TypeScript (general)
- [ ] Add guidelines for React.js (TypeScript)
- [ ] Add guidelines for Angular (TypeScript)
- [ ] Add guidelines for C# (WinUI3)
