### ISSUE TITLE
Add coding guidelines for C++

### ISSUE THREAD

**Issue by klawr** [deeplex/deeplex.github.io#8]
**Problem Description**
There are no coding guidelines for C++

**Proposed Solution**
Add coding guidelines for C++ which contain at least the following information:
 - Which build system to use and how to install it
 - Which package manager is used and a quick description how it is invoked.
 - Formatting to follow
 - Links to copier templates to get started

# Tasks:

- [x] Add compilation information for windows
- [x] Add compilation information for linux
- [x] Add compilation information for esp32 (on windows)
- [ ] Update compilation information for esp32 (CMakePresets.json)
- [ ] Add documentation on testing
- [ ] Add "Adding Libraries to your project"
- [ ] Add "How create (and use) your own libraries"
